<template>
  <Panel class="options">
    <SectionHeader>Runtime Options</SectionHeader>
    <p>
      This form <strong>overrides</strong> the options provided when the firmware
      was flashed. These changes will persist across reboots, but
      <strong>will be reset</strong> when the firmware is reflashed.
      <span v-if="isTx">
        Note: The Binding phrase is <strong>not</strong> remembered, it is a temporary
        field used to generate the binding UID.
      </span>
    </p>

    <div v-if="config?.config" class="inputs">
      <TextInput v-model="bindingPhrase" label="Binding Phrase" placeholder="Binding Phrase" />
      <ArrayInput :model-value="config.config.uid" :label="uidLabel.description" :readonly="true">
        <Tag :fg="uidLabel.fg" :bg="uidLabel.bg">{{ uidLabel.type }}</Tag>
      </ArrayInput>
      <NumericInput v-model="config.options['wifi-on-interval']"
        label="WiFi 'auto on' interval in seconds (leave blank to disable)"
        placeholder="Disabled"
      />
      <NumericInput v-model="config.options['tlm-interval']"
        label="TLM report interval (ms)"
      />
      <NumericInput v-model="config.options['fan-runtime']"
        label="Fan runtime (s)"
      />
      <Checkbox v-model="config.options['is-airport']" label="Use as AirPort Serial device" />
      <NumericInput v-model="config.options['airport-uart-baud']" label="AirPort UART baud" />

      <div class="actions">
        <Button type="primary" @click="save">
          Save
        </Button>
        <Button v-if="config.options.customised" type="danger" small @click="reset">
          Reset runtime options to defaults
        </Button>
      </div>
    </div>
  </Panel>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from 'vue'

import SectionHeader from './components/SectionHeader.vue'
import Panel from '@/components/Panel.vue'
import Tag from './components/Tag.vue'
import TextInput from './components/TextInput.vue'
import ArrayInput from './components/ArrayInput.vue'
import NumericInput from './components/NumericInput.vue'
import Checkbox from './components/Checkbox.vue'
import Button from '@/components/Button.vue'

import { useConfig } from '@/composables/config'
import { useBuildOptions } from '@/composables/build'
import { useAlert } from '@/composables/alert'
// @ts-ignore This import is JS-only
import { uid } from '@/lib/uid'

const bindingPhrase = ref('')
const { config, originalUID, originalUIDType } = useConfig()
const { targetBaseUrl } = useBuildOptions()
const { question, error, info } = useAlert()

watch(bindingPhrase, newValue => {
  if (config.value) {
    if (newValue) {
      config.value.config.uid = uid(newValue)
      config.value.config.uidtype = 'Modified'
    } else {
      config.value.config.uid = originalUID.value
      config.value.config.uidtype = originalUIDType.value
    }
  }
})

async function save() {
  const body = JSON.stringify({
    ...config.value?.options,
    customised: true,
    uid: config.value?.config.uid,
  })

  const response = await fetch(`${targetBaseUrl.value}/options.json`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body,
  })

  if (response.ok) {
    if (await question('Update Succeeded', 'Reboot to take effect', 'Reboot', 'Cancel') !== 'cancel') {
      fetch(`${targetBaseUrl.value}/reboot`, { method: 'POST' })
    }
  } else {
    error('Error saving changes', response.statusText)
  }
}

async function reset() {
  const response = await fetch(`${targetBaseUrl.value}/reset?options`, { method: 'POST' })

  if (response.ok) {
    info('Reset Runtime Options', 'Reset complete, rebooting...')
  } else {
    error('Reset Runtime Options', 'An error occurred resetting runtime options')
  }
}

// eslint-disable-next-line @typescript-eslint/no-shadow
function isEmptyUID(uid: number[]) {
  return !uid || uid.length !== 6 || uid.join(',').endsWith('0,0,0,0')
}

const { isTx } = useBuildOptions()

// eslint-disable-next-line max-lines-per-function, complexity
const uidLabel = computed(() => {
  const uidtype = config.value?.config.uidtype || ''
  if (uidtype.startsWith('Not set')) {
    return {
      bg: '#D50000', fg: 'white',
      type: 'Not set',
      description: 'Using autogenerated binding UID',
    }
  } else if (uidtype === 'Flashed') {
    return {
      bg: '#1976D2', fg: 'white',
      type: uidtype,
      description: 'The binding UID was generated from a binding phrase set at flash time',
    }
  } else if (uidtype === 'Overridden') {
    return {
      bg: '#689F38', fg: 'black',
      type: uidtype,
      description: 'The binding UID has been generated from a binding phrase previously entered into the "binding phrase" field above',
    }
  } else if (uidtype === 'Modified') {
    return {
      bg: '#7c00d5', fg: 'white',
      type: uidtype,
      description: 'The binding UID has been modified, but not yet saved',
    }
  } else if (uidtype === 'Volatile') {
    return {
      bg: '#FFA000', fg: 'white',
      type: uidtype,
      description: 'The binding UID will be cleared on boot',
    }
  } else if (isEmptyUID(config?.value?.config.uid || [])) {
    return {
      bg: '#FFA000', fg: 'white',
      type: 'Not bound',
      description: 'This receiver is unbound and will boot to binding mode',
    }
  } else {
    return {
      bg: '#1976D2', fg: 'white',
      type: 'Bound',
      description: 'This receiver is bound and will boot waiting for connection',
    }
  }
})
</script>

<style lang="postcss" scoped>
.inputs {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-top: 16px;
}

.actions {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-top: 8px;
}
</style>
