<template>
  <div class="options">
    <SectionHeader>Runtime Options</SectionHeader>
    <p>
      This form <strong>overrides</strong> the options provided when the firmware
      was flashed. These changes will persist across reboots, but
      <strong>will be reset</strong> when the firmware is reflashed.
      <span v-if="isTx">
        Note: The Binding phrase is <strong>not</strong> remembered, it is a temporary
        field used to generate the binding UID.
      </span>
    </p>

    <div v-if="config?.config" class="inputs">
      <TextInput v-model="bindingPhrase" label="Binding Phrase" placeholder="Binding Phrase" />
      <ArrayInput :model-value="config.config.uid" :label="uidLabel.description" :readonly="true">
        <div><Tag :fg="uidLabel.fg" :bg="uidLabel.bg">{{ uidLabel.type }}</Tag></div>
      </ArrayInput>
      <NumericInput v-model="config.options['wifi-on-interval']" label="WiFi 'auto on' interval in seconds (leave blank to disable)" />
      <NumericInput v-model="config.options['tlm-interval']" label="TLM report interval (ms)" />
      <NumericInput v-model="config.options['fan-runtime']" label="Fan runtime (s)" />
      <Checkbox v-model="config.options['is-airport']" label="Use as AirPort Serial device" />
      <NumericInput v-model="config.options['airport-uart-baud']" label="AirPort UART baud" />

      <div class="actions">
        <Button @click="save">Save</Button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue'

import SectionHeader from './components/SectionHeader.vue'
import Tag from './components/Tag.vue'
import TextInput from './components/TextInput.vue'
import ArrayInput from './components/ArrayInput.vue'
import NumericInput from './components/NumericInput.vue'
import Checkbox from './components/Checkbox.vue'
import Button from './components/Button.vue'

import { useConfig } from '@/composables/config'
import { useBuildOptions } from '@/composables/build'

const bindingPhrase = ref('')
const { config } = useConfig()

function save() {
  console.log('Saving...')
}

function isEmptyUID(uid: number[]) {
  return !uid || uid.length !== 6 || uid.join(',').endsWith('0,0,0,0')
}

const { isTx } = useBuildOptions()

// eslint-disable-next-line max-lines-per-function, complexity
const uidLabel = computed(() => {
  const uidtype = config.value?.config.uidtype || ''
  if (uidtype.startsWith('Not set')) {
    return {
      bg: '#D50000', fg: 'white',
      type: 'Not set',
      description: 'Using autogenerated binding UID',
    }
  } else if (uidtype === 'Flashed') {
    return {
      bg: '#1976D2', fg: 'white',
      type: uidtype,
      description: 'The binding UID was generated from a binding phrase set at flash time',
    }
  } else if (uidtype === 'Overridden') {
    return {
      bg: '#689F38', fg: 'black',
      type: uidtype,
      description: 'The binding UID has been generated from a binding phrase previously entered into the "binding phrase" field above',
    }
  } else if (uidtype === 'Modified') {
    return {
      bg: '#7c00d5', fg: 'white',
      type: uidtype,
      description: 'The binding UID has been modified, but not yet saved',
    }
  } else if (uidtype === 'Volatile') {
    return {
      bg: '#FFA000', fg: 'white',
      type: uidtype,
      description: 'The binding UID will be cleared on boot',
    }
  } else if (isEmptyUID(config?.value?.config.uid || [])) {
    return {
      bg: '#FFA000', fg: 'white',
      type: 'Not bound',
      description: 'This receiver is unbound and will boot to binding mode',
    }
  } else {
    return {
      bg: '#1976D2', fg: 'white',
      type: 'Bound',
      description: 'This receiver is bound and will boot waiting for connection',
    }
  }
})
</script>

<style lang="postcss" scoped>
.inputs {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-top: 16px;
}

.actions {
  margin-top: 8px;
}
</style>
